version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zay_dev
      MYSQL_USER: zay_prod
      MYSQL_PASSWORD: null
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3001:3000"